DROP TABLE IF EXISTS NOTIFICATIONS;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS ARTISTS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS ACCOUNT_TYPES;
DROP TABLE IF EXISTS ACCOUNT_STATUS;
DROP TABLE IF EXISTS NOTIFICATION_TYPES;
DROP TABLE IF EXISTS TRANSACTION_TYPES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BRANDING_PLANS;
DROP TABLE IF EXISTS COMMISSION_FEES;
DROP TABLE IF EXISTS PHOTOS;
DROP TABLE IF EXISTS REVIEWS;
/*DROP TABLE VENUES;
DROP TABLE DATA_SUITES;*/
