/* Copyright (C) 2017 SocialGuru S.de R.L. - All Rights Reserved */ 

-- SOCIALGURU DATABASE SCHEMA

CREATE TABLE ACCOUNT_TYPES (
	TYPE 		CHAR NOT NULL PRIMARY KEY,
	TYPE_NAME 	VARCHAR(10) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	CONSTRAINT CHECK_TYPE CHECK(TYPE='N' OR TYPE='P' OR TYPE='A' OR TYPE='V'));

/* List of possible types of accounts: 
 * Normal 
 * Promoter
 * Venue
 * Artist */

CREATE TABLE ACCOUNT_STATUS (
	STATUS 		CHAR NOT NULL PRIMARY KEY,
	STATUS_NAME	VARCHAR(10) NOT NULL,
	DESCRIPTION	VARCHAR(100) NOT NULL,
	CONSTRAINT CHECK_STATUS CHECK(STATUS='A' OR STATUS='D' OR STATUS='P' OR STATUS='C'));

/* List of possible status of an account: 
 * Active
 * Down
 * Pending
 * Cancelled */

CREATE TABLE TRANSACTION_TYPES (
	TYPE	CHAR NOT NULL PRIMARY KEY,
	TYPE_NAME	VARCHAR(10) NOT NULL,
	DESCRIPTION	VARCHAR(50) NOT NULL,
	CONSTRAINT CHECK_TYPE CHECK(TYPE='T' OR TYPE='D' OR TYPE='C' OR TYPE='R' OR TYPE='B'));

/* List of possible types of transactions:
 * Transfering money to another account (concept of paying for a service) 'T'
 * Payment for data plan (account to socialguru) 'D'
 * Returning a coupon (digital money) to a customer from socialguru 'C'
 * Returning money to customer (due to a failure in the system) 'R'
 * Payment for branding (customer to socialguru) 'B' */

CREATE TABLE CUSTOMERS ( 
	CUST_ID 		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME 		VARCHAR(30) NOT NULL,
	LAST_NAME 		VARCHAR(30),
	ADDR1			VARCHAR(50),
	ADDR2			VARCHAR(50),
	ZIPCODE			INT(5),
	COUNTRY			VARCHAR(15) NOT NULL,
	MEMBER_SINCE 	DATE NOT NULL)
	AUTO_INCREMENT = 1;

CREATE TABLE ACCOUNTS (
	ACCOUNT_ID		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CUST_ID			INT NOT NULL,
	ACCOUNT_TYPE 	CHAR NOT NULL,
	ACCOUNT_STATUS	CHAR NOT NULL,
	PHONE_NUMBER	VARCHAR(15),
	COMPANY_NAME	VARCHAR(30),
	USERNAME		VARCHAR(12),
	EMAIL			VARCHAR(30),
	PASSWORD		VARCHAR(15),
	CURRENT_BALANCE	FLOAT(10,2),
	PREV_BALANCE	FLOAT(10,2),
	DATE_CREATED	DATE NOT NULL,
	LAST_CHECKOUT	TIMESTAMP,
	LAST_SIGN_IN	TIMESTAMP,
	FOREIGN KEY(CUST_ID) REFERENCES CUSTOMERS(CUST_ID),
	FOREIGN KEY(ACCOUNT_TYPE) REFERENCES ACCOUNT_TYPES(TYPE),
	FOREIGN KEY(ACCOUNT_STATUS) REFERENCES ACCOUNT_STATUS(STATUS))
	AUTO_INCREMENT = 1;

CREATE TABLE TRANSACTIONS (
	TXN_ID		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ACCOUNT_ID	INT NOT NULL,
	TXN_TYPE	CHAR NOT NULL,
	AMOUNT		FLOAT(10,2) NOT NULL,
	DESCRIPTION VARCHAR(50) NOT NULL,
	TXN_TT		TIMESTAMP NOT NULL,
	FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID),
	FOREIGN KEY(TXN_TYPE) REFERENCES TRANSACTION_TYPES(TYPE))
	AUTO_INCREMENT = 1;

CREATE TABLE DATA_SUITES (
	SUITE_ID 	CHAR NOT NUL PRIMARY KEY,
	SUITE_NAME	VARCHAR(15) NOT NULL,
	S
	)

CREATE TABLE BRANDING_PLANS (
	BRANDING_ID		CHAR NOT NULL PRIMARY KEY,
	)

DROP TABLE TRANSACTIONS;
DROP TABLE ACCOUNTS;
DROP TABLE TRANSACTION_TYPES;
DROP TABLE ACCOUNT_TYPES;
DROP TABLE ACCOUNT_STATUS;
DROP TABLE CUSTOMERS;
